name: On-Prem Python App Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: self-hosted  # Uses the self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Adjust based on your requirements

      - name: Run Python Application
        run: |
          python app.py  # Modify this based on your Python entry file

      - name: Stop existing process (optional)
        run: |
          pkill -f app.py || true  # Stops any running instances of the app

      - name: Start Application in Background
        run: |
          nohup python app.py > app.log 2>&1 &  # Runs the app in the background
